### ISSUE TITLE
See the Azure roles that grant a certain Azure permission

### ISSUE THREAD

**Issue by cnotin** [JulianHayward/AzAdvertizer#11]
**Is your feature request related to a problem? Please describe.**
I want to list the Azure roles that grant a certain Azure permission, either explicitly or not (ie. via a wildcard)
For example, which Azure roles grant this permission `Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials/write`?

**Describe the solution you'd like**
On https://www.azadvertizer.net/azresourceoperationadvertizer_all.html I can find the permission: https://www.azadvertizer.net/azresourceoperationadvertizer_all.html?targetOperation=Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials/write
However I can't list the roles.
There's the "usedByRole" column but its content is hidden. How could I show it?
![image](https://github.com/JulianHayward/AzAdvertizer/assets/550823/a00c028d-ee4b-4900-927c-504f7b7c821f)

**Describe alternatives you've considered**
I found the permission in https://www.azadvertizer.net/resProvOps.json:
```
{"n":"d7","a":"userAssignedIdentities/federatedIdentityCredentials","b":"Federated Identity Credentials","c":"Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials/write","d":"Add or update Federated Identity Credential","e":"Add or update a Federated Identity Credential","i":"","r":"cv,fz,kn,lp"}
```
Then understood that the roles are:
```
"r":"cv,fz,kn,lp"
```

So I found them in https://www.azadvertizer.net/js/resProvOpsLookup.js and obtained:
* Azure Red Hat OpenShift Federated Credential Role
* Contributor
* Managed Identity Contributor
* Owner

Or did I miss something or another feature?

Or, implement it myself :)

**Additional context**
Thanks for this great tool!

**Comment by JulianHayward** [comment]
@cnotin true detective, the solution too obvious :) ? Please let me know your thoughts to make it more self explanatory
![image](https://github.com/JulianHayward/AzAdvertizer/assets/45695032/7126ebca-84e7-469c-824c-88c118b95b10)

**Comment by cnotin** [comment]
Ah indeed thank! I totally missed it since I thought it was a filter like the ResourceProvider field on the left ;)

Perhaps change its label to "Show UsedByRole in table" with a checkbox instead of true/false dropdown. Alternatively, you could add a message in the cell where it says "values displayName (Id) are hidden..." describing that there's this feature above the table to show it.

**Comment by JulianHayward** [comment]
backlogged, thx
