### ISSUE TITLE
Find changes on Resource Provider Operations

### ISSUE THREAD

**Issue by wilfriedwoivre** [JulianHayward/AzAdvertizer#12]
**Is your feature request related to a problem? Please describe.**
We deploy only custom role on Azure, and between 2 deployments we seen some changes with missing permission from the previous one.

**Describe the solution you'd like**
As Policy Alias change, can you add Operation Provider changes.

**Describe alternatives you've considered**
Implement myself a similar solution.

**Additional context**
Feel free to contact me if you want

**Comment by JulianHayward** [comment]
hey @wilfriedwoivre as discussed, at the moment not at sight to publish change tracking for resProvOps. Let us know if you publish s.th. - thanks.
