### ISSUE TITLE
Track differences between sovereign clouds and commercial Azure?

### ISSUE THREAD

**Issue by sdolgin** [JulianHayward/AzAdvertizer#13]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am trying to determine if a built-in policy definition is available in US Gov, China, etc. Without having access to these cloud platforms, I don't know if that information is available anywhere.

**Describe the solution you'd like**
I thought to myself, "I would LOVE if this information was available as part of the AzAdvertizer solution."

**Describe alternatives you've considered**
I've tried looking through the [Azure Policy](https://github.com/Azure/azure-policy) repo but it is cumbersome. Additionally, I don't know for certain if this is a good way to infer what is and isn't in government clouds based on the contents of this repo.

**Additional context**
Having a good source of reference that is up-to-date would be helpful. Especially for customers that are trying to modify ALZ to deploy successfully to sovereign clouds.

**Comment by JulianHayward** [comment]
backlogged
