### ISSUE TITLE
AzureUSGovernment Policy Availability

### ISSUE THREAD

**Issue by glsutter** [JulianHayward/AzAdvertizer#14]
I believe this is a feature request. Custom ALZ initiatives and policies include an alzCloudEnvironments metadata field that includes the environments in which the initiative can be used, e.g., AzureCloud, AzureUSGovernment. Currently, we have found no way to filter on that alzCloudEnvironments field. But that would be very desirable for those of us who need to support multiple environments. 

Please allow filtering on alzCloudEnvironments metadata when looking at at All Azure Policy Definitions or All Azure Policy Initiatives.

**Describe alternatives you've considered**
PowerShell script for read ALZ policies and initiatives and filter based on alzCloudEnvironment metadata. 

**Additional context**
\Unfortunately, we have found that the inclusion of an environment in alzCloudEnvironments does NOT guarantee a policy exists in our account. For example, many of the ALZ initiatives reference built-in policies that are missing. But we are assuming this is a problem with our account since some of the missing policies were created over 3 years ago.

**Comment by JulianHayward** [comment]
@glsutter 
for policyDefinitions you could play with the following filters:
<img width="772" alt="image" src="https://github.com/user-attachments/assets/465bb6be-7b27-4e35-99db-77fdd8cb1f8c">

I´ll add your ask to the backlog, definitely a valid feature request.

The issue of missing builtIn definitions in sovereign alz policySets is something that is looked at.

If you have a sovereign tenant and would be willing to help enhance AzAdvertizer for sovereign vs public cloud builtIn policy/set insights (..) then please ping me on LinkedIn.

**Comment by JulianHayward** [comment]
strike
