### ISSUE TITLE
Unable to Import csv into Excel

### ISSUE THREAD

**Issue by quantumburnz** [JulianHayward/AzAdvertizer#15]
**Describe the bug**
I tried exporting policies in both semicolon and csv format. When I import this into Excel, some of the lines get split, presumably because some of the names and descriptions have either commas or semicolons.

**To Reproduce**
1. In Excel, Go to Data -> From Text/CSV
2. Load data

**Expected behavior**
The exports should have the delimiter escaped so they can be loaded in Excel.

**Comment by JulianHayward** [comment]
@quantumburnz thanks for reporting, should be fixed. rc was newly \n displayNames/Descriptions.

**Comment by quantumburnz** [comment]
New csv export seems great, thanks @JulianHayward !
