### ISSUE TITLE
Service and CRUD Columns

### ISSUE THREAD

**Issue by jwgarrett** [JulianHayward/AzAdvertizer#4]
**Is your feature request related to a problem? Please describe.**
I would like to organize the roles based upon service such as Kubernetes, and CRUD (create/read/update/delete).

**Describe the solution you'd like**
Would you please create a service column and CRUD column to make sorting easier?

**Describe alternatives you've considered**
I have considered pivot tabling in excel, but it would only be a static solution.

**Additional context**
I appreciate the help and thank you in advance.

**Comment by JulianHayward** [comment]
@jwgarrett to my knowledge category/service information per role is not available via ARM (if you are referring to the categorization we find in the portal). Can you please draw and example what the CRUD column would look like?

**Comment by jwgarrett** [comment]
I would like to have the Effective Operations column included in the csv export here please. https://www.azadvertizer.net/azrolesadvertizer_all.html

**Comment by JulianHayward** [comment]
@jwgarrett please, more details :)

* the summary 
   * e.g. read:1;write;0 (one column)
   * one column per ops type

| read | write |
| --- | ---|
| 1 | 0 |

* the full list of effective ops
   * that would make the csv too large, I think

**Comment by JulianHayward** [comment]
@jwgarrett please update

**Comment by jwgarrett** [comment]
I like the idea of one column per ops type. It would be very helpful.
<html>
<body>


read | write
-- | --
1 | 0


</body>
</html>

**Comment by JulianHayward** [comment]
@jwgarrett can you please share the use case having this information in the csv file? thanks

**Comment by jwgarrett** [comment]
I will use them to create pivot tables and decide if a role is privileged or not.

**Comment by JulianHayward** [comment]
added to backlog - closing, but updating you here once released
