### ISSUE TITLE
JSON Compare not showing 2.x Version

### ISSUE THREAD

**Issue by mundayn** [JulianHayward/AzAdvertizer#5]
This policy initiative is on version 2.1.1, but the JSON Compare only allows selection of the 1.x versions.

![image](https://github.com/JulianHayward/AzAdvertizer/assets/19361863/f893aed9-cb7d-43fb-b995-dfec50e114d3)

**To Reproduce**
1. Go to ['...'](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Private-DNS-Zones.html)
2. Sctoll down to JSON compare.
3. Click dropdowns

**Expected behavior**
See all versions, including 2.x

**Screenshots**
![image](https://github.com/JulianHayward/AzAdvertizer/assets/19361863/83736455-c0f2-4cb2-b81d-d0fd2af221ad)

![image](https://github.com/JulianHayward/AzAdvertizer/assets/19361863/79dde239-0a0b-42e2-8391-fc27cbd96241)

**Comment by JulianHayward** [comment]
@mundayn thanks for reporting, should be fixed with todays release.

**Comment by JulianHayward** [comment]
closed
