### ISSUE TITLE
Export current filter as URL link

### ISSUE THREAD

**Issue by kamfaima** [JulianHayward/AzAdvertizer#6]
Perhaps I missed this, but it would be nice if you could export the filters in use as a URL link. Then the recipient of the link could simply click on it and the filters would be automatically applied. This is in preference to telling them to click on filter x, then type "123", then deselect "abc", etc.

**Comment by JulianHayward** [comment]
@kamfaima some capabilities already have links embedded - which one are you relating?

**Comment by kamfaima** [comment]
So let's say I have filtered the list of policies by Type ALZ, State GA, and Effect DINE, and I want to share the filtered results with the customer. Instead of telling the customer to do: "under the Type dropdown, select ALZ, then under the State dropdown, select GA, then under Effect, choose deployIfNotExists", I'd be able to copy a link (e.g. URL with all the filtersin the header/address) that represents the current filter and share it with the customer.

**Comment by JulianHayward** [comment]
@kamfaima yes nice idea, but not sure this is possible. If you want to run some doable check -> https://ag-grid.com/javascript-data-grid/getting-started

**Comment by kamfaima** [comment]
I'm sorry, I'm not sure what I'm supposed to do at that link? I'm not a front-end dev. 😆

**Comment by JulianHayward** [comment]
all right I´ll add the idea to the backlog - closing for now.
