### ISSUE TITLE
No delegated permissions shown in EntraID API permissions

### ISSUE THREAD

**Issue by cjtous1** [JulianHayward/AzAdvertizer#8]
**Describe the bug**
When I browse to https://www.azadvertizer.net/azEntraIdAPIpermissionsAdvertizer.html and filter for "Delegated" in the type, there are no permissions listed.

**To Reproduce**
1. Go to 'https://www.azadvertizer.net/azEntraIdAPIpermissionsAdvertizer.html'
2. Click on 'Type'
3. Select to 'Delegated'
4. No permissions are listed

**Expected behavior**
A list of delegated permissions.

**Browser (please complete the following information):**
 - Browser: Microsoft Edge
 - Version 121.0.2277.83

**Comment by JulianHayward** [comment]
thanks for reporting @cjtous1 - fixed with yesterday's release
