### ISSUE TITLE
Can't deploy the policy "Management port access from the Internet should be blocked". It contains errors

### ISSUE THREAD

**Issue by Kamil-Kramek** [JulianHayward/AzAdvertizer#9]
**Describe the bug**

When deploying the policy "Management port access from the Internet should be blocked" I receive the below error:

_**A function or parameter in policy '6ab34426-e940-4545-bab3-8ce9fd039a50' could not be validated. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner exception 'Evaluation result of language expression '[[parameters('ports')]' is type 'String', expected type is 'Array'.'.**_

<br><br>

**To Reproduce**
1. Go to Azure portal -> Policy
2. Create a new policy
3. Into Policy Definition paste JSON of a policy from this link: https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deny-MgmtPorts-From-Internet.json
4. Click Save
<br><br>

**Expected behavior**
A policy should be creted

**Screenshots**
![image](https://github.com/JulianHayward/AzAdvertizer/assets/166635579/85a70a68-59f5-4c53-a3ab-1e0ffc6c1959)

**Browser (please complete the following information):**
N/A

**If smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by JulianHayward** [comment]
@Kamil-Kramek please open the issue at the es repo

**Comment by Kamil-Kramek** [comment]
@JulianHayward Thanks for the reply. After opening the issue I noticed it's not your repo. Opened a new issue there.

**Comment by Springstone** [comment]
Hi, just for completeness, be aware that policies in the enterprise scale repo as specially formatted for Enterprise Scale, and cannot be deployed directly. In order to deploy, please remove the escape character `[[` should be `[` - you need to remove one of the leading brackets and it should deploy fine.
